apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-cubix-cn.fullname" . }}
  labels:
    {{- include "spring-cubix-cn.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: management
      port: 8081
      protocol: TCP
      targetPort: management
  selector:
    {{- include "spring-cubix-cn.selectorLabels" . | nindent 4 }}
